name: Build Images

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up secret file
        env:
          DEBUG_PASSWORD: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
          DEBUG_SECRET_KEY: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
        run:
          echo $DEBUG_PASSWORD >> secrets.txt
          echo $DEBUG_SECRET_KEY >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2

      - name: Build HTTP container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            asher4hs/upstream-server:latest
            asher4hs/upstream-server:${{ github.sha }}
          secrets: |
            "github_username=${{ secrets.PERSONAL_GITHUB_USERNAME }}"
            "github_token=${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}"